name: CI workflows
run-name: Push to ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:18

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install
        shell: bash
        run: npm ci
      - name: run eslint
        shell: bash
        run: npm run lint
